### ISSUE TITLE
Feature Request: auto-disable list

### ISSUE THREAD

**Issue by DrReD** [lunu-bounir/audio-equalizer#17]
There are sites that won't work with audio-equalizer. Some would just grab the audio and play their sounds with their own settings. Those are, at worst, a slight nuisance.
But a few egregious ones would just refuse to play anything whenever the extension is enabled and this, regardless the state of the "Enable Equalizer" flag in the equalizer popup.

Since chrome won't provide an override-list for extensions, one has to disable the equalizer extension manually every time, reload the website (in order to hear the audio) and afterwards remember to bring audio-equalizer back to life. -This- is _definitively_ a nuisance, —dear chrome developers—.

While it's not this extension fault, an internal override-list would avoid all the pain and provide a seamless experience. It can even be done without ui changes, by leveraging the profiles as in: disabled@domain.

Alternatively, if the "Enable Equalizer" flag would disable the extension more thoroughly, prevent  code injections / grabs of media nodes, we could at least avoid the extra trips outside the extension.
And perhaps, if the flag was saved within profiles, we could still create our own block-lists by leveraging the "name@domain" profiles.

**Comment by lunu-bounir** [comment]
> But a few egregious ones would just refuse to play anything whenever the extension is enabled

Can you provide a sample? I need to be sure the extension is not breaking the audio playback, whether the equalizer is successfully connected or not.

> Since chrome won't provide an override-list for extensions, one has to disable the equalizer extension manually every time

If you need the equalizer to inject its script into a few websites, use the right-click "This Can Read and Change Site Date" option. You can limit the extension to selected hostnames.

> Alternatively, if the "Enable Equalizer" flag would more thoroughly disable the extension and prevent any code injection

Currently, the extension finds the media sources and attaches the filters whether they are used or not. This way, the preamp works even when levels are set to the default values. This behavior looks intuitive to me. We need to find the faulty code and fix that instead of not injecting the code.

**Comment by lunu-bounir** [comment]
As of the next release (0.2.2), you can add a custom profile that includes the `.disabled` keyword to disable the extension on a hostname. Read more on the FAQ 10

https://add0n.com/audio-equalizer.html?rev

**Comment by DrReD** [comment]
Great, it works. Thank you very much!
Audio-equalizer is now even more user-friendly. Lovin' it. :)

I'm curious if it can match the domain only, or the sub-page too, as in:
`disabled@domain.com/subpage`

**Comment by lunu-bounir** [comment]
The latest commit improves the profile matching algorithm to include pathname matching. Give it a try, and let me know how it works
